name = "OceanAnalysis"
uuid = "935d77d6-d85b-49cc-a465-c336e8287d34"
authors = ["dankelley <kelley.dan@gmail.com>"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GibbsSeaWater = "9a22fb26-0b63-4589-b28e-8f9d0b5c3d05"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
GibbsSeaWater = "0.1.4"
NCDatasets = "0.14.8"
Plots = "1.40.13"
